$(document).ready(function() {

    $('#coursework').children().on('click', function(){
        if($(this).hasClass('active')){
            $(this).children().eq(1).slideToggle(250);
            $(this).children().eq(0).removeClass('activeTitle');
            $(this).removeClass('active');
        }
        else{
            $(this).siblings().each(function(){
                if($(this).hasClass('active')){
                    $(this).removeClass('active');
                    $(this).children().eq(0).removeClass('activeTitle');
                    $(this).children().eq(1).slideToggle(250);
                }
            });
          $(this).addClass('active');
          $(this).children().eq(0).addClass('activeTitle');
          $(this).children().eq(1).slideToggle(250);
        }
    });
    $('#involvement').children().on('click', function(){
         if($(this).hasClass('active')){
             $(this).children().eq(1).slideToggle(250);
             $(this).children().eq(0).removeClass('activeTitle');
             $(this).removeClass('active');
         }
         else{
             $(this).siblings().each(function(){
                 if($(this).hasClass('active')){
                     $(this).removeClass('active');
                     $(this).children().eq(0).removeClass('activeTitle');
                     $(this).children().eq(1).slideToggle(250);
                 }
             });
           $(this).addClass('active');
           $(this).children().eq(0).addClass('activeTitle');
           $(this).children().eq(1).slideToggle(250);
         }
     });
     $('#workExperience').children().on('click', function(){
        if($(this).hasClass('active')){
             $(this).children().eq(1).slideToggle(250);
             $(this).children().eq(0).removeClass('activeTitle');
             $(this).removeClass('active');
         }
         else{
             $(this).siblings().each(function(){
                 if($(this).hasClass('active')){
                     $(this).removeClass('active');
                     $(this).children().eq(0).removeClass('activeTitle');
                     $(this).children().eq(1).slideToggle(250);
                 }
             });
           $(this).addClass('active');
           $(this).children().eq(0).addClass('activeTitle');
           $(this).children().eq(1).slideToggle(250);
         }
     });
    $('#volExp').children().on('click', function(){
         if($(this).hasClass('active')){
             $(this).children().eq(1).slideToggle(250);
             $(this).children().eq(0).removeClass('activeTitle');
             $(this).removeClass('active');
         }
         else{
             $(this).siblings().each(function(){
                 if($(this).hasClass('active')){
                     $(this).removeClass('active');
                     $(this).children().eq(0).removeClass('activeTitle');
                     $(this).children().eq(1).slideToggle(250);
                 }
             });
           $(this).addClass('active');
           $(this).children().eq(0).addClass('activeTitle');
           $(this).children().eq(1).slideToggle(250);
         }
     });
    $('#projectU').children().on('click', function(){
         if($(this).hasClass('active')){
             $(this).children().eq(1).slideToggle(250);
             $(this).children().eq(0).removeClass('activeTitle');
             $(this).removeClass('active');
         }
         else{
             $(this).siblings().each(function(){
                 if($(this).hasClass('active')){
                     $(this).removeClass('active');
                     $(this).children().eq(0).removeClass('activeTitle');
                     $(this).children().eq(1).slideToggle(250);
                 }
             });
           $(this).addClass('active');
           $(this).children().eq(0).addClass('activeTitle');
           $(this).children().eq(1).slideToggle(250);
         }
     });

});
